import Foundation

/// App UI language. Protocol strings, device names, and media metadata retain their original values.
enum MacPlayLocalization {
    static var language = "system"

    static var effectiveLanguage: String {
        let requested = language == "system" ? (Locale.preferredLanguages.first ?? "en") : language
        let code = requested.lowercased()
        if code.hasPrefix("zh") {
            return code.contains("hant") || code.contains("tw") || code.contains("hk") || code.contains("mo") ? "zh-Hant" : "zh-Hans"
        }
        return "en"
    }

    static func translate(_ text: String) -> String {
        let code = effectiveLanguage
        guard code != "zh-Hans", !text.isEmpty else { return text }
        let target = code == "zh-Hant" ? 0 : 1
        if let translation = translations[text] { return target == 0 ? translation.0 : translation.1 }
        // Status details can include a translated app hint followed by the original system explanation.
        if text.contains("\n") { return text.components(separatedBy: "\n").map(translate).joined(separator: "\n") }
        if text.hasPrefix("将在"),text.hasSuffix("秒后重试连接。") {
            let seconds=text.dropFirst(2).dropLast(7)
            return code == "zh-Hant" ? "將在\(seconds)秒後重試連線。" : "Retrying in \(seconds) seconds."
        }
        for (expression, traditional, english) in patterns {
            let range = NSRange(text.startIndex..<text.endIndex, in: text)
            if expression.firstMatch(in: text, range: range) != nil {
                let result = expression.stringByReplacingMatches(in: text, range: range, withTemplate: target == 0 ? traditional : english)
                return result.replacingOccurrences(of: "内建显示器", with: code == "zh-Hant" ? "內建顯示器" : "Built-in Display")
                    .replacingOccurrences(of: "外接显示器", with: code == "zh-Hant" ? "外接顯示器" : "External Display")
            }
        }
        return text
    }

    private static let translations: [String: (String, String)] = [
        "严格按屏幕物理像素显示":("嚴格按螢幕實體像素顯示","Display at exact physical pixel size"),
        "原生像素模式全屏显示。关闭严格像素显示后，窗口适配屏幕并可等比例调整大小，不改变请求分辨率。":("原生像素模式全螢幕顯示。關閉嚴格像素顯示後，視窗適配螢幕並可等比例調整大小，不改變請求解析度。","Native resolution uses full screen. Turn off exact pixel sizing to fit the window to the screen and resize it proportionally without changing the requested resolution."),
        "CarPlay已连接":("CarPlay已連線","CarPlay connected"),
        "首帧已解码，CarPlay画面窗口已打开":("首幀已解碼，CarPlay畫面視窗已開啟","First frame decoded; CarPlay window opened"),

        "连接启动超时": ("連線啟動逾時", "Connection startup timed out"),
        "iPhone网络连接超时": ("iPhone網路連線逾時", "iPhone network connection timed out"),
        "CarPlay视频连接超时": ("CarPlay視訊連線逾時", "CarPlay video connection timed out"),
        "iPhone网络连接已断开": ("iPhone網路連線已中斷", "iPhone network connection lost"),
        "网络已切换，请读取或填写当前网络密码。": ("網路已切換，請讀取或填寫目前網路密碼。", "Network changed. Read or enter the current network password."),
        "请读取当前网络并填写对应密码。": ("請讀取目前網路並填寫對應密碼。", "Read the current network and enter its password."),
        "当前Wi-Fi与连接配置不一致": ("目前Wi-Fi與連線設定不一致", "Current Wi-Fi does not match the connection settings"),
        "等待自动重连": ("等待自動重新連線", "Waiting to reconnect"),
        "无线连接被动断开时自动重连": ("無線連線被動中斷時自動重新連線", "Automatically reconnect after a wireless disconnection"),
        "开源许可": ("開源授權", "Open-source license"),
        "日志": ("日誌", "Logs"),
        "版本、更新与日志": ("版本、更新與日誌", "Version, updates and logs"),
        "当前版本": ("目前版本", "Current version"),
        "构建版本": ("組建版本", "Build"),
        "运行架构": ("執行架構", "Architecture"),
        "软件更新": ("軟體更新", "Software updates"),
        "自动检查更新": ("自動檢查更新", "Check for updates automatically"),
        "检查更新": ("檢查更新", "Check for updates"),
        "尚未检查更新": ("尚未檢查更新", "Updates have not been checked"),
        "正在检查更新…": ("正在檢查更新…", "Checking for updates…"),
        "检查更新失败": ("檢查更新失敗", "Could not check for updates"),
        "当前已是最新版本": ("目前已是最新版本", "You are up to date"),
        "未找到正式发行版": ("未找到正式發行版", "No stable release found"),
        "发现新版本": ("發現新版本", "Update available"),
        "下载更新": ("下載更新", "Download update"),
        "查看发行说明": ("查看發行說明", "View release notes"),
        "项目主页": ("專案首頁", "Project website"),
        "稍后": ("稍後", "Later"),
        "下载与安装由你确认。": ("下載與安裝由你確認。", "You choose when to download and install."),
        "导出日志": ("匯出日誌", "Export logs"),
        "诊断日志": ("診斷日誌", "Diagnostic logs"),
        "暂无日志可导出": ("暫無日誌可匯出", "No logs to export"),
        "日志已导出": ("日誌已匯出", "Logs exported"),
        "日志导出失败": ("日誌匯出失敗", "Could not export logs"),
        "无法打开链接": ("無法開啟連結", "Could not open the link"),
        "点击下载更新，安装由你确认。": ("點擊下載更新，安裝由你確認。", "Tap to download. You choose when to install."),
        "应用启动或回到前台时每天检查一次GitHub正式发行版。": ("應用程式啟動或回到前景時每天檢查一次GitHub正式發行版。", "Checks GitHub stable releases once a day on launch or return to the foreground."),
        "应用启动或回到前台时每天检查一次GitHub正式发行版。发现新版时提示，下载与安装由你确认。": ("應用程式啟動或回到前景時每天檢查一次GitHub正式發行版。發現新版時提示，下載與安裝由你確認。", "Checks GitHub stable releases once a day on launch or return to the foreground. Updates are announced; you choose when to download and install."),
        "最新发行版暂无适合当前芯片的安装包，请查看发行说明。": ("最新發行版暫無適合目前晶片的安裝套件，請查看發行說明。", "The latest release has no installer for this processor. See the release notes."),
        "导出当前连接日志，不包含设置文件或认证文件，并过滤网络密码与设备标识。": ("匯出目前連線日誌，不包含設定檔案或認證檔案，並過濾網路密碼與裝置識別碼。", "Exports connection logs without settings or authentication files, filtering network passwords and device identifiers."),
        "导出最近连接记录，过滤网络密码、认证内容与设备标识。": ("匯出最近連線記錄，過濾網路密碼、認證內容與裝置識別碼。", "Exports recent connection logs, filtering network passwords, authentication data and device identifiers."),
        "下载与安装由你确认。自动更新提醒需要通知权限；未授权时在应用内提示。": ("下載與安裝由你確認。自動更新提醒需要通知權限；未授權時在應用程式內提示。", "You choose when to download and install. Automatic update notifications require notification permission; otherwise reminders appear in the app."),
        "跟随系统": ("跟隨系統", "Follow System"),
        "简体中文": ("简体中文", "简体中文"),
        "繁體中文": ("繁體中文", "繁體中文"),
        "连接": ("連線", "Connection"),
        "显示": ("顯示", "Display"),
        "音频": ("音訊", "Audio"),
        "诊断": ("診斷", "Diagnostics"),
        "接收端": ("接收端", "Receiver"),
        "状态": ("狀態", "Status"),
        "自动（上次连接的iPhone）": ("自動（上次連線的iPhone）", "Automatic (last connected iPhone)"),
        "刷新iPhone列表": ("重新整理iPhone列表", "Refresh iPhones"),
        "自动模式优先连接上次成功显示画面的iPhone。切换设备后点击“应用并重新连接”。": ("自動模式優先連線上次成功顯示畫面的iPhone。切換裝置後點擊「套用並重新連線」。", "Automatic mode prefers the iPhone that last displayed CarPlay successfully. Click “Apply and Reconnect” after changing devices."),
        "连接方式": ("連線方式", "Connection Method"),
        "有线CarPlay": ("有線CarPlay", "Wired CarPlay"),
        "无线CarPlay": ("無線CarPlay", "Wireless CarPlay"),
        "通过蓝牙配对后使用共用Wi-Fi连接。": ("透過藍牙配對後使用共用Wi-Fi連線。", "Pair over Bluetooth, then connect using shared Wi-Fi."),
        "通过USB数据线连接，无需填写Wi-Fi信息。": ("透過USB資料線連線，無需填寫Wi-Fi資訊。", "Connect with a USB data cable. Wi-Fi information is not required."),
        "应用": ("應用程式", "Application"),
        "语言": ("語言", "Language"),
        "USB接入时自动启动CarPlay": ("USB接入時自動啟動CarPlay", "Start CarPlay Automatically When iPhone Connects via USB"),
        "允许后台运行": ("允許背景執行", "Allow Background Operation"),
        "关闭主窗口后继续接收，可从菜单栏图标打开窗口或退出。自动启动需要MacPlay保持运行，并在iPhone上解锁和完成信任。": ("關閉主視窗後繼續接收，可從選單列圖示開啟視窗或結束程式。自動啟動需要MacPlay保持執行，並在iPhone上解鎖和完成信任。", "Keep receiving after closing the main window. Use the menu bar icon to reopen a window or quit. Automatic USB connection requires MacPlay to be running and iPhone to be unlocked and trusted."),
        "USB直连": ("USB直接連線", "USB Connection"),
        "设备": ("裝置", "Device"),
        "连接阶段": ("連線階段", "Connection Stage"),
        "刷新USB设备": ("重新整理USB裝置", "Refresh USB Devices"),
        "连接数据线后点击“启动接收”，并在iPhone上解锁、确认信任。USB设备检测会自动刷新。": ("連接資料線後點擊「啟動接收」，並在iPhone上解鎖、確認信任。USB裝置偵測會自動重新整理。", "Connect a USB data cable, click “Start Receiving,” then unlock iPhone and confirm trust. USB device detection refreshes automatically."),
        "共用Wi-Fi": ("共用Wi-Fi", "Shared Wi-Fi"),
        "网络名称（SSID）": ("網路名稱（SSID）", "Network Name (SSID)"),
        "网络密码": ("網路密碼", "Network Password"),
        "网络接口": ("網路介面", "Network Interface"),
        "读取当前网络": ("讀取目前網路", "Read Current Network"),
        "正在读取密码…": ("正在讀取密碼…", "Reading Password…"),
        "读取已保存密码": ("讀取已儲存密碼", "Read Saved Password"),
        "打开定位设置": ("開啟定位設定", "Open Location Settings"),
        "打开蓝牙设置": ("開啟藍牙設定", "Open Bluetooth Settings"),
        "Mac与iPhone需加入同一Wi-Fi，并在两端确认蓝牙配对码。不会创建名为MacPlay的Wi-Fi。填写SSID与共享密码，或授权读取已保存的密码。802.1X企业Wi-Fi的用户名、个人密码或证书不能作为共享密码发送。": ("Mac與iPhone需加入同一Wi-Fi，並在兩端確認藍牙配對碼。不會建立名為MacPlay的Wi-Fi。填寫SSID與共用密碼，或授權讀取已儲存的密碼。802.1X企業Wi-Fi的使用者名稱、個人密碼或憑證不能作為共用密碼傳送。", "Connect Mac and iPhone to the same Wi-Fi and confirm the Bluetooth pairing code on both devices. MacPlay does not create its own Wi-Fi network. Enter the SSID and shared password, or authorize reading the saved password. Usernames, personal passwords, and certificates for 802.1X enterprise Wi-Fi cannot be sent as a shared password."),
        "显示器": ("顯示器", "Monitor"),
        "显示位置": ("顯示位置", "Display On"),
        "内建显示器": ("內建顯示器", "Built-in Display"),
        "外接显示器": ("外接顯示器", "External Display"),
        "默认内建显示器；切换显示器后应用并重新连接。": ("預設內建顯示器；切換顯示器後套用並重新連線。", "The built-in display is the default. Apply and reconnect after switching displays."),
        "视频分辨率": ("影片解析度", "Video Resolution"),
        "分辨率": ("解析度", "Resolution"),
        "屏幕原生像素（避开刘海）": ("螢幕原生像素（避開瀏海）", "Native Screen Pixels (Avoid Notch)"),
        "自定义": ("自訂", "Custom"),
        "宽度（像素）": ("寬度（像素）", "Width (Pixels)"),
        "高度（像素）": ("高度（像素）", "Height (Pixels)"),
        "请求像素": ("請求像素", "Requested Pixels"),
        "原生像素模式默认全屏并避开刘海。其他分辨率按屏幕真实物理像素换算固定窗口，允许拖动标题栏移动，但不能调整窗口大小；超过可见区域的尺寸无法启动。": ("原生像素模式預設全螢幕並避開瀏海。其他解析度按螢幕實際物理像素換算固定視窗，允許拖曳標題列移動，但不能調整視窗大小；超過可見區域的尺寸無法啟動。", "Native pixel mode opens full screen and avoids the notch. Other resolutions use a fixed window mapped to the display’s physical pixels. Drag the title bar to move it; resizing is disabled. A resolution larger than the visible area cannot start."),
        "流畅度": ("流暢度", "Frame Rate"),
        "最高帧率": ("最高影格率", "Maximum Frame Rate"),
        "高帧率为实验请求：120fps协商失败后改用90fps，90fps仍失败则改用60fps。发起CarPlay连接后20秒未启动视频视为失败。": ("高影格率為實驗請求：120fps協商失敗後改用90fps，90fps仍失敗則改用60fps。發起CarPlay連線後20秒未啟動影片視為失敗。", "High frame rates are experimental requests. If 120fps negotiation fails, retry at 90fps, then 60fps. Video not starting within 20 seconds of initiating a CarPlay connection counts as failure."),
        "上报所选分辨率与固定窗口对应的真实物理尺寸，不提供倍率调节。请关闭CarPlay自身的“智能缩放显示”以避免自动缩放。帧率为请求上限。": ("回報所選解析度與固定視窗對應的實際物理尺寸，不提供倍率調整。請關閉CarPlay自身的「智慧縮放顯示」以避免自動縮放。影格率為請求上限。", "Reports the selected resolution and the physical size of the fixed window. Scaling controls are not provided. Turn off Smart Display Zoom in CarPlay to avoid automatic scaling. Frame rate is a requested maximum."),
        "CarPlay声音": ("CarPlay聲音", "CarPlay Audio"),
        "播放iPhone音频": ("播放iPhone音訊", "Play iPhone Audio"),
        "媒体音量": ("媒體音量", "Media Volume"),
        "通话音量": ("通話音量", "Call Volume"),
        "输出设备": ("輸出裝置", "Output Device"),
        "输入设备": ("輸入裝置", "Input Device"),
        "系统默认设备": ("系統預設裝置", "System Default Device"),
        "刷新设备": ("重新整理裝置", "Refresh Devices"),
        "媒体与通话音量实时生效；设备切换后应用并重新连接。默认跟随系统设备，麦克风使用需要系统授权。": ("媒體與通話音量即時生效；裝置切換後套用並重新連線。預設跟隨系統裝置，麥克風使用需要系統授權。", "Media and call volume changes take effect immediately. Apply and reconnect after switching devices. The system’s default devices are used by default; microphone access requires permission."),
        "认证与日志": ("認證與記錄", "Authentication and Logs"),
        "认证文件": ("認證檔案", "Authentication Files"),
        "文件已就绪，等待iPhone验证": ("檔案已就緒，等待iPhone驗證", "Files Ready; Awaiting iPhone Verification"),
        "缺少文件": ("缺少檔案", "Files Missing"),
        "导入认证文件": ("匯入認證檔案", "Import Authentication Files"),
        "打开认证目录": ("開啟認證目錄", "Open Authentication Folder"),
        "打开日志": ("開啟記錄", "Open Log"),
        "刷新状态": ("重新整理狀態", "Refresh Status"),
        "安装包内置实验性认证材料；本机已导入的文件优先使用。": ("安裝套件內建實驗性認證資料；本機已匯入的檔案優先使用。", "The app includes experimental authentication material. Files already imported on this Mac take priority."),
        "最近日志": ("最近記錄", "Recent Logs"),
        "暂无日志": ("暫無記錄", "No Logs Yet"),
        "关于": ("關於", "About"),
        "基于LIVI，参考DiPlay。保留原作者版权，沿用GPL-3.0-or-later。支持有线与无线CarPlay连接。": ("基於LIVI，參考DiPlay。保留原作者著作權，沿用GPL-3.0-or-later。支援有線與無線CarPlay連線。", "Based on LIVI, with reference to DiPlay. Original copyrights are preserved under GPL-3.0-or-later. Supports wired and wireless CarPlay."),
        "停止接收": ("停止接收", "Stop Receiving"),
        "显示画面": ("顯示畫面", "Show CarPlay"),
        "应用并重新连接": ("套用並重新連線", "Apply and Reconnect"),
        "启动接收": ("啟動接收", "Start Receiving"),
        "显示MacPlay": ("顯示MacPlay", "Show MacPlay"),
        "显示CarPlay": ("顯示CarPlay", "Show CarPlay"),
        "退出MacPlay": ("結束MacPlay", "Quit MacPlay"),
        "选择identity.pk8和certificate.p7b": ("選擇identity.pk8和certificate.p7b", "Select identity.pk8 and certificate.p7b"),
        "尚未启动接收": ("尚未啟動接收", "Receiver Not Started"),
        "连接iPhone后启动接收端。": ("連接iPhone後啟動接收端。", "Connect iPhone, then start the receiver."),
        "尚未读取网络": ("尚未讀取網路", "Network Not Read Yet"),
        "接收服务未启动": ("接收服務尚未啟動", "Receiver Service Not Started"),
        "Wi-Fi未开启或没有可用接口": ("Wi-Fi未開啟或沒有可用介面", "Wi-Fi is off or no interface is available"),
        "已读取当前Wi-Fi名称和信道": ("已讀取目前Wi-Fi名稱和頻道", "Current Wi-Fi name and channel read"),
        "系统定位服务已关闭。读取Wi-Fi名称需要在系统设置中开启定位服务。": ("系統定位服務已關閉。讀取Wi-Fi名稱需要在系統設定中開啟定位服務。", "Location Services are off. Enable them in System Settings to read the Wi-Fi name."),
        "读取Wi-Fi名称需要定位权限；点击“读取当前网络”后按系统提示允许。": ("讀取Wi-Fi名稱需要定位權限；點擊「讀取目前網路」後按系統提示允許。", "Location permission is required to read the Wi-Fi name. Click “Read Current Network” and allow access when prompted."),
        "定位权限未允许。请在“隐私与安全性→定位服务”中允许MacPlay后重试。": ("定位權限未允許。請在「隱私權與安全性→定位服務」中允許MacPlay後重試。", "Location permission is denied. Allow MacPlay in Privacy & Security → Location Services, then retry."),
        "已获定位权限，但系统未返回Wi-Fi名称。请确认Mac已连接Wi-Fi后重试。": ("已獲定位權限，但系統未傳回Wi-Fi名稱。請確認Mac已連接Wi-Fi後重試。", "Location access is allowed, but the system did not return a Wi-Fi name. Check that Mac is connected to Wi-Fi, then retry."),
        "当前网络使用802.1X企业认证（用户名/密码或证书）。MacPlay的无线握手不支持发送这类凭据，请改用个人Wi-Fi、热点或USB连接。": ("目前網路使用802.1X企業認證（使用者名稱/密碼或憑證）。MacPlay的無線握手不支援傳送這類憑證，請改用個人Wi-Fi、熱點或USB連線。", "This network uses 802.1X enterprise authentication (username/password or certificate). MacPlay cannot send these credentials during wireless negotiation. Use a personal Wi-Fi network, hotspot, or USB connection."),
        "请先读取当前网络名称。": ("請先讀取目前網路名稱。", "Read the current network name first."),
        "正在读取钥匙串；如有系统提示，请授权MacPlay访问该网络密码。": ("正在讀取鑰匙圈；如有系統提示，請授權MacPlay存取該網路密碼。", "Reading Keychain. If prompted, authorize MacPlay to access this network’s password."),
        "网络已切换，请重新读取密码。": ("網路已切換，請重新讀取密碼。", "The network changed. Read the password again."),
        "已读取保存的密码，点击“应用并重新连接”使用网络凭据。": ("已讀取儲存的密碼，點擊「套用並重新連線」使用網路憑證。", "Saved password read. Click “Apply and Reconnect” to use it."),
        "钥匙串未返回可用密码，请手动填写。": ("鑰匙圈未傳回可用密碼，請手動填寫。", "Keychain did not return a usable password. Enter it manually."),
        "钥匙串未找到该网络的可读取密码，请手动填写。": ("鑰匙圈未找到該網路的可讀取密碼，請手動填寫。", "No readable password for this network was found in Keychain. Enter it manually."),
        "未获准读取网络密码，请重新授权或手动填写。": ("未獲准讀取網路密碼，請重新授權或手動填寫。", "Permission to read the network password was not granted. Authorize access again or enter it manually."),
        "无法读取系统USB设备列表": ("無法讀取系統USB裝置列表", "Cannot read the system USB device list"),
        "等待USB握手，请保持iPhone解锁": ("等待USB握手，請保持iPhone解鎖", "Waiting for USB negotiation; keep iPhone unlocked"),
        "未检测到USB连接的iPhone": ("未偵測到USB連接的iPhone", "No iPhone Connected via USB"),
        "所选分辨率超过当前屏幕的可见区域，无法按物理像素比例显示。请选择较低分辨率，或使用原生像素全屏模式。": ("所選解析度超過目前螢幕的可見區域，無法按物理像素比例顯示。請選擇較低解析度，或使用原生像素全螢幕模式。", "The selected resolution exceeds the display’s visible area and cannot be shown at its physical pixel size. Choose a lower resolution or native pixel full-screen mode."),
        "系统未返回显示器真实尺寸，无法上报固定窗口的物理大小。": ("系統未傳回顯示器實際尺寸，無法回報固定視窗的物理大小。", "The system did not return the display’s physical dimensions, so the fixed window’s physical size cannot be reported."),
        "检测到多台USB连接的iPhone，请先选择要连接的设备。": ("偵測到多台USB連接的iPhone，請先選擇要連接的裝置。", "Multiple iPhones are connected via USB. Select the device to connect first."),
        "所选iPhone缺少当前连接方式的设备记录，请选择已配对或USB接入的设备完成首次连接。": ("所選iPhone缺少目前連線方式的裝置記錄，請選擇已配對或USB接入的裝置完成首次連線。", "The selected iPhone has no device record for this connection method. Choose a paired or USB-connected iPhone for the first connection."),
        "缺少认证文件": ("缺少認證檔案", "Authentication Files Missing"),
        "请在诊断页面导入有使用权限的配套认证文件。": ("請在診斷頁面匯入有使用權限的配套認證檔案。", "Import matching authentication files you are authorized to use on the Diagnostics page."),
        "当前Wi-Fi采用企业认证": ("目前Wi-Fi採用企業認證", "Current Wi-Fi Uses Enterprise Authentication"),
        "无线CarPlay握手不支持802.1X用户名/密码或证书，请改用个人Wi-Fi、热点或USB连接。": ("無線CarPlay握手不支援802.1X使用者名稱/密碼或憑證，請改用個人Wi-Fi、熱點或USB連線。", "Wireless CarPlay negotiation does not support 802.1X usernames/passwords or certificates. Use a personal Wi-Fi network, hotspot, or USB connection."),
        "无线连接缺少网络信息": ("無線連線缺少網路資訊", "Wireless Network Information Missing"),
        "请先读取当前Wi-Fi名称。": ("請先讀取目前Wi-Fi名稱。", "Read the current Wi-Fi name first."),
        "找不到应用资源目录": ("找不到應用程式資源目錄", "Application resources folder not found"),
        "接收进程已退出": ("接收程序已結束", "Receiver Process Exited"),
        "请查看诊断日志。": ("請查看診斷記錄。", "See the diagnostic log."),
        "正在启动接收服务": ("正在啟動接收服務", "Starting Receiver Service"),
        "准备蓝牙握手与共用Wi-Fi连接。": ("準備藍牙握手與共用Wi-Fi連線。", "Preparing Bluetooth negotiation and shared Wi-Fi connection."),
        "准备USB连接与配件认证。": ("準備USB連線與配件認證。", "Preparing USB connection and accessory authentication."),
        "启动失败": ("啟動失敗", "Start Failed"),
        "接收已停止": ("接收已停止", "Receiving Stopped"),
        "可以调整设置后重新启动。": ("可以調整設定後重新啟動。", "Adjust settings, then start again."),
        "将自动降低帧率请求并重新连接。": ("將自動降低影格率請求並重新連線。", "The frame rate request will be reduced and the connection retried automatically."),
        "已收到视频配置": ("已收到影片設定", "Video Configuration Received"),
        "CarPlay画面窗口已打开": ("CarPlay畫面視窗已開啟", "CarPlay Window Opened"),
        "已接收CarPlay视频，画面窗口已打开": ("已接收CarPlay影片，畫面視窗已開啟", "CarPlay video received and window opened"),
        "请在诊断页面打开认证目录，放入有使用权限的配套文件。": ("請在診斷頁面開啟認證目錄，放入有使用權限的配套檔案。", "Open the authentication folder on the Diagnostics page and add matching files you are authorized to use."),
        "蓝牙握手未完成": ("藍牙握手未完成", "Bluetooth Negotiation Incomplete"),
        "请在iPhone蓝牙页面与Mac完成配对，并确认两端配对码。": ("請在iPhone藍牙頁面與Mac完成配對，並確認兩端配對碼。", "Pair iPhone with Mac in iPhone’s Bluetooth settings and confirm the code on both devices."),
        "蓝牙重连超时": ("藍牙重新連線逾時", "Bluetooth Reconnection Timed Out"),
        "正在刷新iPhone服务信息，请保持iPhone蓝牙开启。": ("正在重新整理iPhone服務資訊，請保持iPhone藍牙開啟。", "Refreshing iPhone service information. Keep iPhone Bluetooth on."),
        "连接需要检查": ("連線需要檢查", "Connection Needs Attention"),
        "配件认证已通过": ("配件認證已通過", "Accessory Authentication Passed"),
        "正在协商CarPlay连接": ("正在協商CarPlay連線", "Negotiating CarPlay Connection"),
        "已发送连接参数": ("已傳送連線參數", "Connection Parameters Sent"),
        "等待iPhone连接接收端": ("等待iPhone連接接收端", "Waiting for iPhone to Connect"),
        "USB通信已建立，正在识别配件": ("USB通訊已建立，正在識別配件", "USB communication established; identifying accessory"),
        "iPhone已接受配件识别": ("iPhone已接受配件識別", "iPhone accepted accessory identification"),
        "配件认证已通过，正在建立CarPlay会话": ("配件認證已通過，正在建立CarPlay工作階段", "Accessory authenticated; establishing CarPlay session"),
        "已发送CarPlay连接参数": ("已傳送CarPlay連線參數", "CarPlay connection parameters sent"),
        "USB通信失败": ("USB通訊失敗", "USB Communication Failed"),
        "无法打开iPhone的CarPlay服务，请解锁并确认信任后重新连接。": ("無法開啟iPhone的CarPlay服務，請解鎖並確認信任後重新連線。", "Cannot open iPhone’s CarPlay service. Unlock iPhone, confirm trust, then reconnect."),
        "iPhone已拔出": ("iPhone已拔出", "iPhone Unplugged"),
        "连接后端启动失败": ("連線後端啟動失敗", "Connection Backend Failed to Start"),
        "连接后端已退出": ("連線後端已結束", "Connection Backend Exited"),
        "收到连接请求": ("收到連線請求", "Connection Request Received"),
        "正在协商认证与音视频": ("正在協商認證與影音", "Negotiating Authentication, Audio, and Video"),
        "CarPlay会话已建立": ("CarPlay工作階段已建立", "CarPlay Session Established"),
        "等待视频流": ("等待影片串流", "Waiting for Video Stream"),
        "CarPlay会话已建立，等待视频流": ("CarPlay工作階段已建立，等待影片串流", "CarPlay session established; waiting for video"),
        "连接已断开": ("連線已中斷", "Disconnected"),
        "重新启动接收可再次连接": ("重新啟動接收可再次連線", "Start receiving again to reconnect"),
        "CarPlay会话已断开，可点击“应用并重新连接”": ("CarPlay工作階段已中斷，可點擊「套用並重新連線」", "CarPlay session disconnected. Click “Apply and Reconnect” to reconnect."),
        "返回设置": ("返回設定", "Return to Settings"),
        "已打开MacPlay设置窗口": ("已開啟MacPlay設定視窗", "MacPlay settings window opened"),
        "可切换至MacPlay设置窗口": ("可切換至MacPlay設定視窗", "Switch to the MacPlay settings window"),
        "会话错误": ("工作階段錯誤", "Session Error"),
        "接收服务启动失败": ("接收服務啟動失敗", "Receiver Service Failed to Start"),
        "等待iPhone连接": ("等待iPhone連線", "Waiting for iPhone"),
        "无线CarPlay接收已启用，请在系统蓝牙中配对iPhone": ("無線CarPlay接收已啟用，請在系統藍牙中配對iPhone", "Wireless CarPlay receiving enabled. Pair iPhone in system Bluetooth settings."),
        "有线CarPlay接收已启用，请连接USB数据线": ("有線CarPlay接收已啟用，請連接USB資料線", "Wired CarPlay receiving enabled. Connect a USB data cable."),
        "等待CarPlay视频": ("等待CarPlay影片", "Waiting for CarPlay Video"),
        "视频尚未建立，暂不打开空白画面窗口。": ("影片尚未建立，暫不開啟空白畫面視窗。", "Video is not ready. A blank CarPlay window will not be opened."),
        "您确定要断开与iPhone的连接吗？": ("您確定要中斷與iPhone的連線嗎？", "Disconnect from iPhone?"),
        "断开连接": ("中斷連線", "Disconnect"),
        "取消": ("取消", "Cancel"),
        "关闭CarPlay窗口将断开与iPhone的连接，并返回MacPlay主窗口。": ("關閉CarPlay視窗將中斷與iPhone的連線，並返回MacPlay主視窗。", "Closing the CarPlay window disconnects iPhone and returns to the MacPlay main window."),
    ]

    private static let patterns: [(NSRegularExpression, String, String)] = [
        (try! NSRegularExpression(pattern: "^信道：(\\d+)$"), "頻道：$1", "Channel: $1"),
        (try! NSRegularExpression(pattern: "^已检测到(\\d+)台iPhone$"), "已偵測到$1台iPhone", "$1 iPhone(s) Detected"),
        (try! NSRegularExpression(pattern: "^未获准读取网络密码（系统状态码(-?\\d+)），请重新授权或手动填写。$"), "未獲准讀取網路密碼（系統狀態碼$1），請重新授權或手動填寫。", "Permission to read the network password was not granted (system status $1). Authorize access again or enter it manually."),
        (try! NSRegularExpression(pattern: "^无法读取网络密码（系统状态码(-?\\d+)），请手动填写。$"), "無法讀取網路密碼（系統狀態碼$1），請手動填寫。", "Cannot read the network password (system status $1). Enter it manually."),
        (try! NSRegularExpression(pattern: "^(\\d+)fps协商未启动视频，已改用(\\d+)fps重连。$"), "$1fps協商未啟動影片，已改用$2fps重新連線。", "Video did not start after $1fps negotiation. Reconnecting at $2fps."),
        (try! NSRegularExpression(pattern: "^(\\d+)fps协商未启动视频，改用(\\d+)fps重连$"), "$1fps協商未啟動影片，改用$2fps重新連線", "Video did not start after $1fps negotiation. Reconnecting at $2fps"),
        (try! NSRegularExpression(pattern: "^(内建显示器|外接显示器) · (\\d+)×(\\d+)像素 · (\\d+)Hz · (\\d+)×(\\d+)mm$"), "$1 · $2×$3像素 · $4Hz · $5×$6mm", "$1 · $2×$3 pixels · $4Hz · $5×$6mm"),
    ]
}

/// Translate at display time so a language change immediately refreshes stored status messages.
func L(_ text: String) -> String { MacPlayLocalization.translate(text) }
